[package]
name = "toast"
version = "0.1.0"
edition = "2021"
authors = ["Emma Plante"]

[dependencies]
bootloader = "0.9.23"
volatile = "0.2.6"
spin = "0.9.8"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]