[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-toast.json"

[target.'cfg(target_os = "none")']
rustflags = ["--cfg", "testing"]

[toolchain]
channel = "nightly"